/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package fabra.io.javasdk.models.operations;



public class GetNamespacesRequest {
    public GetNamespacesQueryParams queryParams;
    public GetNamespacesRequest withQueryParams(GetNamespacesQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
