/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package fabra.io.javasdk.models.operations;



public class GetSchemaRequest {
    public GetSchemaQueryParams queryParams;
    public GetSchemaRequest withQueryParams(GetSchemaQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
