/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package fabra.io.javasdk.models.operations;



public class GetTablesRequest {
    public GetTablesQueryParams queryParams;
    public GetTablesRequest withQueryParams(GetTablesQueryParams queryParams) {
        this.queryParams = queryParams;
        return this;
    }
    
}
