/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package fabra.io.javasdk.models.operations;

import fabra.io.javasdk.utils.SpeakeasyMetadata;

public class GetTablesRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=connectionID")
    public Long connectionID;
    public GetTablesRequest withConnectionID(Long connectionID) {
        this.connectionID = connectionID;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=namespace")
    public String namespace;
    public GetTablesRequest withNamespace(String namespace) {
        this.namespace = namespace;
        return this;
    }
    
}
